### ISSUE TITLE
Allow executing different entry points than `_start`

### ISSUE THREAD

**Issue by gzurl** [vmware-labs/mod_wasm#25]
When executing a Wasm module, `_start` is the function executed by default.

We might want to invoke different entry points into a single module.
A new directive (i.e.: WasmEntryPoint <value>) could do the job.

**Comment by dpfens** [comment]
@gzurl this issue can be closed after the recent merge.

**Comment by gzurl** [comment]
Yeah, thanks @dpfens for your contribution!
