### ISSUE TITLE
Build.sh doesnot  work for the ubuntu system

### ISSUE THREAD

**Issue by navneet-rathi** [vmware-labs/mod_wasm#36]
### Describe the bug

It gives an error while building like

root@demo:/home/nrathi/mod_wasm/mod_wasm# ./build.sh 
SUDO_GID=1000
LESSOPEN=| /usr/bin/lesspipe %s
MAIL=/var/mail/root
USER=root
SHLVL=1
HOME=/root
OLDPWD=/home/nrathi/mod_wasm
LC_CTYPE=C.UTF-8
SUDO_UID=1000
LOGNAME=root
_=./build.sh
TERM=xterm-256color
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
LANG=C.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SUDO_COMMAND=/bin/bash
SHELL=/bin/bash
SUDO_USER=nrathi
LESSCLOSE=/usr/bin/lesspipe %s %s
PWD=/home/nrathi/mod_wasm/mod_wasm
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
+ which libtool
/usr/bin/libtool
+ which pkg-config
/usr/bin/pkg-config
+ echo [Building mod_wasm]
[Building mod_wasm]
+ 
+ pwd
+ dirname -- ./build.sh
+ cd -- .
+ SCRIPT_DIR=/home/nrathi/mod_wasm/mod_wasm
+ realpath /home/nrathi/mod_wasm/mod_wasm/modules/wasm
+ MOD_WASM_DIR=/home/nrathi/mod_wasm/mod_wasm/modules/wasm
+ realpath /home/nrathi/mod_wasm/mod_wasm/../wasm_runtime
+ WASM_RUNTIME_PATH=/home/nrathi/mod_wasm/wasm_runtime
+ realpath /home/nrathi/mod_wasm/mod_wasm/../dist
+ DIST_DIR=/home/nrathi/mod_wasm/dist
+ [ -z ]
+ realpath ../httpd
+ HTTPD_DIR=/home/nrathi/mod_wasm/httpd
+ uname -m
+ ARCH=x86_64
+ echo [Deleting binaries]
[Deleting binaries]
+ rm -fv /home/nrathi/mod_wasm/mod_wasm/modules/wasm/mod_wasm.o
+ rm -fv /home/nrathi/mod_wasm/mod_wasm/modules/wasm/mod_wasm.lo
+ rm -fv /home/nrathi/mod_wasm/mod_wasm/modules/wasm/mod_wasm.slo
+ rm -fv /home/nrathi/mod_wasm/mod_wasm/modules/wasm/mod_wasm.la
+ rm -fv /home/nrathi/mod_wasm/mod_wasm/modules/wasm/.libs/mod_wasm.o
+ rm -fv /home/nrathi/mod_wasm/mod_wasm/modules/wasm/.libs/mod_wasm.la
+ rm -fv /home/nrathi/mod_wasm/mod_wasm/modules/wasm/.libs/mod_wasm.lai
+ rm -fv /home/nrathi/mod_wasm/mod_wasm/modules/wasm/.libs/mod_wasm.a
+ rm -fv /home/nrathi/mod_wasm/mod_wasm/modules/wasm/.libs/mod_wasm.so
+ echo [Building mod_wasm]
[Building mod_wasm]
+ echo [mod_wasm: compiling]
[mod_wasm: compiling]
+ cd /home/nrathi/mod_wasm/mod_wasm/modules/wasm
+ pkg-config --cflags apr-1 apr-util-1
+ /usr/share/apr-1.0/build/libtool --verbose --mode=compile x86_64-linux-gnu-gcc -I/home/nrathi/mod_wasm/httpd -DLINUX -D_REENTRANT -D_GNU_SOURCE -I/usr/include/apr-1.0 -I/home/nrathi/mod_wasm/wasm_runtime/include -shared -c mod_wasm.c
libtool: compile:  x86_64-linux-gnu-gcc -I/home/nrathi/mod_wasm/httpd -DLINUX -D_REENTRANT -D_GNU_SOURCE -I/usr/include/apr-1.0 -I/home/nrathi/mod_wasm/wasm_runtime/include -c mod_wasm.c  -fPIC -DPIC -o .libs/mod_wasm.o
mod_wasm.c:16:10: fatal error: httpd.h: No such file or directory
   16 | #include "httpd.h"
      |          ^~~~~~~~~
compilation terminated.
+ echo [mod_wasm: linking]
[mod_wasm: linking]
+ /usr/share/apr-1.0/build/libtool --verbose --mode=link x86_64-linux-gnu-gcc -L/home/nrathi/mod_wasm/wasm_runtime/target/release -lwasm_runtime -o mod_wasm.la -rpath /dist/modules -module -avoid-version mod_wasm.lo
libtool:   error: 'mod_wasm.lo' is not a valid libtool object
+ echo [Installing module]
[Installing module]
+ mkdir -p /home/nrathi/mod_wasm/dist/modules/
+ cp -v .libs/mod_wasm.so /home/nrathi/mod_wasm/dist/modules/
cp: cannot stat '.libs/mod_wasm.so': No such file or directory
+ echo [Installing httpd.conf]
[Installing httpd.conf]
+ cd /home/nrathi/mod_wasm/mod_wasm
+ mkdir -p /home/nrathi/mod_wasm/dist/conf/
+ cp -v httpd.conf /home/nrathi/mod_wasm/dist/conf/

### Reproduction steps

1.
2.
3.
...

### Expected behavior

Need to manually edit the build script and provided the path for httpd.h

like 
echo "[Building mod_wasm]"

SCRIPT_DIR=$( cd -- "$(dirname -- "$0")" &> /dev/null && pwd )
MOD_WASM_DIR=${MOD_WASM_DIR:-$(realpath "${SCRIPT_DIR}/modules/wasm")}
WASM_RUNTIME_PATH=${WASM_RUNTIME_PATH:-$(realpath "${SCRIPT_DIR}/../wasm_runtime")}
DIST_DIR=${DIST_DIR:-$(realpath "${SCRIPT_DIR}/../dist")}
if [ -z ${HTTPD_DIR+x} ]
then
#    HTTPD_DIR=$(realpath ../httpd)
    **HTTPD_DIR=/usr/include/apache2/**
fi
ARCH=$(uname -m)

echo "[Deleting binaries]"

rm -fv ${MOD_WASM_DIR}/mod_wasm.o
rm -fv ${MOD_WASM_DIR}/mod_wasm.lo
rm -fv ${MOD_WASM_DIR}/mod_wasm.slo
rm -fv ${MOD_WASM_DIR}/mod_wasm.la

**Comment by gzurl** [comment]
Thanks @navneet-rathi for reporting this!

The `build.sh` is intended to be used as a _quick shortcut_ for developers to avoid Autotools and compile mod_wasm with development versions of Apache server (see https://github.com/vmware-labs/mod_wasm/tree/main/mod_wasm#readme), so it's very dependant on your local setup.

The script will look for `HTTPD_DIR` current value and if it doesn't exist, will default to `../httpd`.
So you can redefine the value this way:
```
$ HTTPD_DIR=/path/to/your/httpd ./build.sh
```
or
```
$ export HTTPD_DIR=/path/to/your/httpd
$ ./build.sh
```

Anyway, I'm adding some improvements in PR #35 to emit a warning message in case it uses the default value.

**Comment by gzurl** [comment]
@navneet-rathi, PR #35 is now merged!
